# huurwoning/docker-compose.yml
services:
  app:
    logging:
      driver: gcplogs
      options:
        gcp-project: "huurwoning"
    build: .
    init: true
    shm_size: "2gb" # Increase shared memory size
    environment:
      - CHROME_BIN=/usr/bin/chromium-browser
      - CHROME_PATH=/usr/lib/chromium/
    env_file:
      - .env
    mem_limit: 4g # Set memory limit to 4GB
    mem_reservation: 2g # Reserve 2GB of memory
